### ISSUE TITLE
FileAssetHandle Compile Error

### ISSUE THREAD

**Issue by mariobadr** [mariobadr/RPGTK4#8]
Error	5	error C2440: 'return' : cannot convert from 'std::basic_ifstream<char,std::char_traits<char>>' to 'bool'	c:\users\mario\documents\github\rpgtk4\include\trans4\assets\files\FileAssetHandle.hpp	32	1	trans4

It won't compile this file because of the Exists function. I can change it to: return ifstream(path_).good(); but I'm not sure if this is your intended functionality.

**Comment by chutchinson** [comment]
This is correct; I didn't realize MSVC didn't overload implicit bool conversion operator for ifstream...
