### ISSUE TITLE
Compile Error on Loading Game Manifest

### ISSUE THREAD

**Issue by mariobadr** [mariobadr/RPGTK4#9]
The line auto manifest = assets_.Load<GameManifest>("file://main.gam"); in Engine.hpp won't compile. It says "no instance of overloaded function matches the argument list", even though it does. I don't know enough about templates so I can't figure out what's wrong.

**Comment by chutchinson** [comment]
Must be a MSVC issue; compiles fine with GCC 4.9.2. I'll check it out.

**Comment by chutchinson** [comment]
This compiles fine with VC18 (VS2013) - the line should read:

    auto manifest = assets_.Load<GameManifest>("file://main.gam");

**Comment by mariobadr** [comment]
I don't think this is what caused the problem, but I changed all "class" keywords to "struct" as some were conflicting, and everything seems to work fine now.

**Comment by chutchinson** [comment]
I noticed the same issue... I actually swapped them back from struct -> class in a previous commit and it looks like that got caught in the mix. I fixed it again.
